### ISSUE TITLE
Provide a way to explicitly create ND tensors

### ISSUE THREAD

**Issue by epignatelli** [BHoM/MachineLearning_Toolkit#11]
#### Description:

We need to provide a way to create multidimesional tensors from lists and nested lists.
This will be achieved by:
- `Modify.VStack(List<Tensor> tensors)`, `Modify.HStack(List<Tensor> tensors)` `Modify.Stack(List<Tensor> tensors, int dim)` to merge multiple tensors
- `Modify.Unsqueeze(Tensor tensor, List<int> dims)`, to only expand on dimension.
- `Modify.Squeeze(Tensor tensor, List<int> dims)`, to contract useless dimensions

**Comment by BingWangUS** [comment]
This is also an odd behaviour that I observed. In some cases, the tensor will have a return from python as one number instead of a list. Then it will fail when using Tensor ToList. It sounds like a ToNumber method is needed. However, it will be great to change ToList method to a general convert method. 

This could be a separate issue if needed but think it may be related to this work here.

**Comment by jamesramsden-bh** [comment]
Closed as related functionality has now been removed from this toolkit.
