### ISSUE TITLE
Namespaces should be restricted to BH.*.MachineLearning

### ISSUE THREAD

**Issue by epignatelli** [BHoM/MachineLearning_Toolkit#44]
#### Broken rules:

There are currently some methods within a `Vision` namespace.

#### Suggestions to restore compliance:

To clarify to the user when he/she is going into python land, it would be good to restrict the namespaces to only `MachineLearning`.

**Comment by al-fisher** [comment]
@epignatelli - I think this was probably raised as a result of my comment and testing of machine learning methods. 

From our follow up conversation - with clarifying how Python and ML Toolkits are structured - I think we changed my mind. 😄 

It does make sense to inject into the appropriate namespace - as per your example of `BH.Engine.Vision`.
The only point we clarified was that it should be evident to the user where the method being called is being called _from_. i.e. if it is actually in the new `Extensions` folder. 
We already have some pretty good error messages if method fails - saying InstallerPython/ML etc.
Worth continuing to considering mechanisms for letting users know when they are relying on additional packages. Perhaps worth a separate issue as more start testing machinelearning workflows

However happy _this_ issue on restricting namespaces be closed and code and guidance left as is

**Comment by epignatelli** [comment]
Thanks Al!

In the light of our last conversation, I think I woudl lean towards *adding* `Vision` to the namespace, i.e. `BH.Engine.MachineLearning.Vision`, such that we'll have also `BH.Engine.MachineLearning.Text`, `BH.Engine.MachineLearning.Audio`, `BH.Engine.MachineLearning.Geometry` and so on..

What do you think?

**Comment by al-fisher** [comment]
Happy to go with that approach. Does make sense and much clearer on the canvas when you are likely to be relying on _Extensions_ and _Python libraries_ etc.

There will probably be grey areas around methods that do things that question _"do they count as machine learning?"_ in order to put in that namespace - equally the other way round - methods you might want to store elsewhere!

**_However_** let us solve one problem at a time 😄 - can revisit if/or when methods and code crop up.

All sounds good! 👍
